### ISSUE TITLE
Auto Documenting Syntax For Node Commands

### ISSUE THREAD

**Issue by derekr** [qrush/sub#36]
Not quite sure how to tap in to the auto documentation when creating a node based command. Hash bangs are illegal characters and js comments aren't picked up by `sub`.

Tried:

``` js
#!/usr/bin/env node
// # Usage: diy notify
// # Summary: Send a notification to any maker.
// # Help: Be careful!
```

and 

``` js
#!/usr/bin/env node
// Usage: diy notify
// Summary: Send a notification to any maker.
// Help: Be careful!
```

**Comment by markstos** [comment]
This can be closed. The suggestion by @iakobos is simple, intuitive and works.

**Comment by qrush** [comment]
👁️ Catching up here after a long time off... I'd love a PR to allow for parsing comments in different languages. Can close this for now though.
